name: kidkid
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1
module:
  androidX: true

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation:
  provider:
  path_provider:
  dio:
  audioplayers:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  webview_flutter:
  flutter_swiper:
  chewie:
  video_player:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  json_serializable:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  - images/i1.png
  - images/i1_s.png
  - images/i2.png
  - images/i2_s.png
  - images/voice.png
  - images/ai.png

  - images/music/huaban.png
  - images/music/game.png
  - images/music/jiazhang.png

  - images/player/pre.png
  - images/player/playing.png
  - images/player/pause.png
  - images/player/next.png

  - images/demo/poster.png

  - images/sticker/0.png
  - images/sticker/1.png
  - images/sticker/2.png
  - images/sticker/3.png
  - images/sticker/4.png
  - images/sticker/5.png
  - images/sticker/6.png
  - images/sticker/7.png
  - images/sticker/8.png
  - images/sticker/9.png
  - images/sticker/10.png
  - images/sticker/11.png
  - images/sticker/12.png
  - images/sticker/13.png
  - images/sticker/14.png
  - images/sticker/15.png
  - images/sticker/16.png
  - images/sticker/17.png
  - images/sticker/18.png
  - images/sticker/19.png
  - images/sticker/20.png
  - images/sticker/21.png
  - images/sticker/22.png
  - images/sticker/23.png
  - images/sticker/24.png
  - images/sticker/25.png
  - images/sticker/26.png
  - images/sticker/27.png
  - images/sticker/28.png
  - images/sticker/29.png
  - images/sticker/30.png
  - images/sticker/31.png
  - images/sticker/32.png
  - images/sticker/33.png
  - images/sticker/34.png
  - images/sticker/35.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
